import { useEffect, useMemo, useState } from 'react';
import { Download, Save } from 'lucide-react';
import { PageHeader, Field, StatCard, PlanInsight, StatusBadge, ValidationErrors } from '../components/PlannerUI';
import LeadChart from '../components/LeadChart';
import GapVisualizer from '../components/GapVisualizer';
import { KEY_DATA } from '../data/tbmConstants';
import { runAutoPlan } from '../services/autoPlanner';
import { DEFAULT_GAP_SETTINGS } from '../services/advancePlanner';
import { latestMeasured, nextRingNumber, readStored, exportCSV, RECORD_LABELS, recordKind } from '../services/decisionSupport';

export default function SequencePlanner({ringLogs=[],onBatchSave=async()=>{},theme='dark',track='EB'}) {
  const baseline=latestMeasured(ringLogs)||ringLogs.at(-1);
  const [form,setForm]=useState(()=>readStored(`tbm_sequence_session_${track}`,{startRingNum:nextRingNumber(ringLogs),startKey:baseline?.key||'L2',startHLead:baseline?.hLead??0,startVLead:baseline?.vLead??0,alignmentType:'right',radius:500,ringCount:10,targetV:0,leadLimit:55,lookaheadDepth:3}));
  const [allowedTypes,setAllowedTypes]=useState(()=>readStored(`tbm_sequence_types_${track}`,['U','R','L']));
  useEffect(()=>{try{localStorage.setItem(`tbm_sequence_session_${track}`,JSON.stringify(form));localStorage.setItem(`tbm_sequence_types_${track}`,JSON.stringify(allowedTypes));}catch{/* plan remains in memory */}},[track,form,allowedTypes]);
  const [gapSettings]=useState(()=>readStored('tbm_gap_settings',DEFAULT_GAP_SETTINGS));
  const [selection,setSelection]=useState(1);
  const [onlyIssues,setOnlyIssues]=useState(false);
  const [saving,setSaving]=useState(false);
  const [message,setMessage]=useState('');
  const update=(key,value)=>{setForm(prev=>({...prev,[key]:value}));setMessage('');};
  const computation=useMemo(()=>{try{return {result:runAutoPlan({...form,allowedTypes,gapSettings}),errors:[]};}catch(error){return {result:null,errors:[error.message]};}},[form,allowedTypes,gapSettings]);
  const result=computation.result;
  const selected=result?.plannedRings.find(r=>r.step===selection)||result?.plannedRings[0];
  const visible=result?.plannedRings.filter(r=>!onlyIssues||r.assessment.level!=='normal')||[];
  const save=async()=>{if(!result||saving)return;setSaving(true);try{await onBatchSave(result.plannedRings.map(r=>({...r,track,key:r.selectedKey,hLead:r.afterH,vLead:r.afterV,timestamp:new Date().toISOString()})));setMessage('บันทึกแผนแล้ว · ยังไม่ใช่ประวัติการติดตั้งจริง');}catch(error){setMessage(error.message);}finally{setSaving(false);}};
  const exportPlan=()=>exportCSV(`tbm-sequence-plan-${track}.csv`,['Tunnel','Record type','Ring','Key','Width (m)','After H (mm)','After V (mm)','Gap T','Gap B','Gap L','Gap R','Suitability','Reason'],result.plannedRings.map(r=>[track,'planned',r.ringNum,r.selectedKey,r.sizeM,r.afterH,r.afterV,r.gapT,r.gapB,r.gapL,r.gapR,r.suitability,r.reason]));
  return <div className="stack"><PageHeader eyebrow={`Sequence planning · ${track==='EB'?'TBM1':'TBM2'} · Lookahead`} title={`วางแผนคีย์ต่อเนื่อง ${track==='EB'?'TBM1 (EB)':'TBM2 (WB)'}`} description="ค้นหาทางเลือกข้างหน้าสูงสุด 3 ริง โดยให้ผลตรวจ Suitability, Lead และ Gap มาก่อนการลดระยะห่างจากเป้าหมาย" actions={<><button className="btn btn-outline" disabled={!result} onClick={exportPlan}><Download size={16}/>Export CSV</button><button className="btn btn-acc" disabled={!result||saving} onClick={save}><Save size={16}/>{saving?'กำลังบันทึก…':'เก็บเป็นแผนคาดการณ์'}</button></>}/>
    <div className="workspace-grid"><div className="card"><div className="section-heading"><h3>เงื่อนไขการวางแผน</h3><span className="source-label">{baseline?RECORD_LABELS[recordKind(baseline)]:'ไม่มีข้อมูลสนาม'}</span></div><div className="form-grid"><Field label="ริงเริ่มต้น"><input value={form.startRingNum} onChange={e=>update('startRingNum',e.target.value)}/></Field><Field label="จำนวนริง (1–100)"><input type="number" min="1" max="100" step="1" value={form.ringCount} onChange={e=>update('ringCount',e.target.value)}/></Field><Field label="คีย์ก่อนเริ่ม"><select value={form.startKey} onChange={e=>update('startKey',e.target.value)}>{Object.keys(KEY_DATA).map(k=><option key={k}>{k}</option>)}</select></Field><Field label="แนวราบ"><select value={form.alignmentType} onChange={e=>update('alignmentType',e.target.value)}><option value="straight">ทางตรง</option><option value="right">โค้งขวา</option><option value="left">โค้งซ้าย</option></select></Field><Field label="H Lead เริ่มต้น (mm)"><input type="number" step=".01" value={form.startHLead} onChange={e=>update('startHLead',e.target.value)}/></Field><Field label="V Lead เริ่มต้น (mm)"><input type="number" step=".01" value={form.startVLead} onChange={e=>update('startVLead',e.target.value)}/></Field><Field label="รัศมีโค้ง (m)"><input type="number" min=".01" disabled={form.alignmentType==='straight'} value={form.radius} onChange={e=>update('radius',e.target.value)}/></Field><Field label="Lead limit (mm)"><input type="number" min="1" value={form.leadLimit} onChange={e=>update('leadLimit',e.target.value)}/></Field></div><details className="mt-5"><summary>เงื่อนไขเพิ่มเติม</summary><div className="form-grid mt-4"><Field label="เป้าหมาย V (mm)"><input type="number" value={form.targetV} onChange={e=>update('targetV',e.target.value)}/></Field><Field label="จำนวนริงที่มองล่วงหน้า"><select value={form.lookaheadDepth} onChange={e=>update('lookaheadDepth',e.target.value)}><option value={1}>1 ริง</option><option value={2}>2 ริง</option><option value={3}>3 ริง</option></select></Field></div><p className="section-note mt-4">ชนิดเซ็กเมนต์ที่อนุญาต</p><div className="page-actions mt-2">{['U','R','L'].map(type=><label key={type} className="flex gap-2 items-center"><input type="checkbox" checked={allowedTypes.includes(type)} onChange={e=>setAllowedTypes(prev=>e.target.checked?[...prev,type]:prev.filter(t=>t!==type))}/>{type}</label>)}</div></details><p className="section-note mt-4">ความยาวและ Lead required คำนวณตามชนิดคีย์ของแต่ละริง</p></div>
    <div className="stack"><ValidationErrors errors={computation.errors}/>{result && <><div className="stat-grid"><StatCard label="ระยะรวมตามเซ็กเมนต์" value={result.totalDistanceM} unit="m"/><StatCard label="ริงที่ต้องตรวจทาน" value={result.summary.problemCount} unit="ริง" onClick={()=>setOnlyIssues(true)}/><StatCard label="Gap คาดการณ์ต่ำสุด" value={result.summary.minGap} unit="mm"/></div><PlanInsight summary={result.summary}><p>Auto ต่อเนื่องไม่มีพิกัดสำรวจ จึงยังไม่ได้ตรวจ DTA offset · Gap เป็นค่าคาดการณ์</p></PlanInsight><div className="card"><h3>Lead ตามลำดับริง</h3><LeadChart rings={result.plannedRings} limit={Number(form.leadLimit)} theme={theme} onSelect={r=>setSelection(r.step)}/></div></>}{message && <p role="status">{message}</p>}</div></div>
    {result && <><div className="section-heading"><h3>ลำดับคีย์ · {result.ringCount} ริง</h3><label className="flex gap-2 items-center section-note"><input type="checkbox" checked={onlyIssues} onChange={e=>setOnlyIssues(e.target.checked)}/>เฉพาะริงที่ต้องตรวจทาน</label></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>ริง / คีย์</th><th className="numeric">ความยาว (m)</th><th className="numeric">After H (mm)</th><th className="numeric">After V (mm)</th><th className="numeric">Gap ต่ำสุด (mm)</th><th>Suitability</th><th>ผลตรวจ</th></tr></thead><tbody>{visible.map(r=><tr key={r.ringNum} className={selected?.step===r.step?'selected-row':''}><td><button className="row-button" onClick={()=>setSelection(r.step)}>{r.ringNum} · {r.selectedKey}</button></td><td className="numeric">{r.sizeM}</td><td className="numeric">{r.afterH}</td><td className="numeric">{r.afterV}</td><td className="numeric">{r.assessment.minGap}</td><td>{r.suitability}</td><td><StatusBadge level={r.assessment.level}/></td></tr>)}{!visible.length && <tr><td colSpan={7}>ไม่มีริงที่ต้องตรวจทานภายใต้เกณฑ์นี้</td></tr>}</tbody></table></div>{selected && <div className="two-columns"><div className="card"><div className="section-heading"><h3>{selected.ringNum} · {selected.selectedKey}</h3><StatusBadge level={selected.assessment.level}/></div><p>{selected.reason}</p>{selected.assessment.issues.map(i=><p className="section-note mt-2" key={i.code}>{i.message}</p>)}</div><GapVisualizer gapT={selected.gapT} gapB={selected.gapB} gapL={selected.gapL} gapR={selected.gapR} warnThreshold={gapSettings.warnThreshold} blockThreshold={gapSettings.criticalThreshold}/></div>}</>}
  </div>;
}
